New logging common.c
pi-hole/FTL pull request #1141
Opened 2021-05-27 11:49 UTC by yubiuser

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/FTL/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

Change the logging mode to the new style

2021-05-27 11:55 UTC, DL6ER requested changes
Thanks, I have only a few suggestions.

2021-05-27 11:55 UTC, DL6ER commented on src/database/common.c
> +		log_debug(DEBUG_DATABASE, "Closing FTL database in %s() (%s:%i)", func, file, line);
Please fix indentation here, too.
```suggestion
	log_debug(DEBUG_DATABASE, "Closing FTL database in %s() (%s:%i)", func, file, line);
```

2021-05-27 11:55 UTC, DL6ER commented on src/database/common.c
> +		log_err("ERROR: SQL query \"%s\" failed: %s",
This will result in `ERR: ERROR: ...`
```suggestion
		log_err("SQL query \"%s\" failed: %s",
```

2021-05-27 11:55 UTC, DL6ER commented on src/database/common.c
> +			log_warn("Counter table not initialized, database not available");
Above you assigned `database not available` to `ERR`. I agree.
```suggestion
			log_err("Counter table not initialized, database not available");
```

2021-05-27 11:55 UTC, DL6ER commented on src/database/common.c
> +			log_warn("Network table not initialized, database not available");
```suggestion
			log_err("Network table not initialized, database not available");
```

2021-05-27 11:55 UTC, DL6ER commented on src/database/common.c
> +			log_warn("Unable to unify clients in network table, database not available");
```suggestion
			log_err("Unable to unify clients in network table, database not available");
```

2021-05-27 11:55 UTC, DL6ER commented on src/database/common.c
> +			log_warn("Network-addresses table not initialized, database not available");
```suggestion
			log_err("Network-addresses table not initialized, database not available");
```

2021-05-27 11:55 UTC, DL6ER commented on src/database/common.c
> +			log_warn("Message table not initialized, database not available");
```suggestion
			log_err("Message table not initialized, database not available");
```

2021-05-27 11:55 UTC, DL6ER commented on src/database/common.c
> +			log_warn("Column additional_info not initialized, database not available");
```suggestion
			log_err("Column additional_info not initialized, database not available");
```

2021-05-27 11:55 UTC, DL6ER commented on src/database/common.c
> +			log_warn("Network addresses table not initialized, database not available");
```suggestion
			log_err("Network addresses table not initialized, database not available");
```

2021-05-27 11:55 UTC, DL6ER commented on src/database/common.c
> +			log_warn("Aliasclients table not initialized, database not available");
```suggestion
			log_err("Aliasclients table not initialized, database not available");
```

2021-05-27 11:55 UTC, DL6ER commented on src/database/common.c
> +			log_warn("Long-term database not initialized, database not available");
```suggestion
			log_err("Long-term database not initialized, database not available");
```

2021-05-27 11:55 UTC, DL6ER commented on src/database/common.c
> +		log_warn("Memory allocation failed in db_get_int db, with ID = %u (%i)", ID, ret);
Memory issues are always pretty severe.

```suggestion
		log_err("Memory allocation failed in db_get_int db, with ID = %u (%i)", ID, ret);
```

2021-05-27 11:55 UTC, DL6ER commented on src/database/common.c
> +		log_warn("Memory allocation failed in db_get_FTL_property with ID = %u (%i)", ID, ret);
```suggestion
		log_err("Memory allocation failed in db_get_FTL_property with ID = %u (%i)", ID, ret);
```

2021-05-27 11:55 UTC, DL6ER commented on src/database/common.c
> +log_debug(DEBUG_DATABASE,"dbquery: \"%s\"", querystr);
```suggestion
	log_debug(DEBUG_DATABASE, "dbquery: \"%s\"", querystr);
```

2021-05-27 11:55 UTC, DL6ER commented on src/database/common.c
> +		log_debug(DEBUG_DATABASE,"         ---> Result %i (int)", result);
```suggestion
		log_debug(DEBUG_DATABASE, "         ---> Result %i (int)", result);
```

2021-05-27 11:55 UTC, DL6ER commented on src/database/common.c
> +		log_debug(DEBUG_DATABASE,"         ---> No data");
```suggestion
		log_debug(DEBUG_DATABASE, "         ---> No data");
```

2021-05-27 11:55 UTC, DL6ER commented on src/database/common.c
> +	log_debug(DEBUG_DATABASE,"dbquery: \"%s\"", querystr);
```suggestion
	log_debug(DEBUG_DATABASE, "dbquery: \"%s\"", querystr);
```

2021-05-27 11:55 UTC, DL6ER commented on src/database/common.c
> +		log_debug(DEBUG_DATABASE,"         ---> Result %f (double)", result);
```suggestion
		log_debug(DEBUG_DATABASE, "         ---> Result %f (double)", result);
```

2021-05-27 11:55 UTC, DL6ER commented on src/database/common.c
> +		log_debug(DEBUG_DATABASE,"         ---> No data");
```suggestion
		log_debug(DEBUG_DATABASE, "         ---> No data");
```

2021-05-27 11:56 UTC, DL6ER requested changes
This is an error.

2021-05-27 11:56 UTC, DL6ER commented on src/database/common.c
>  	}
```suggestion
```

2021-05-27 12:30 UTC, yubiuser commented
What am I doing with 

```
if(config.debug & DEBUG_ARP && dbID >= 0)
```

Translates to
```
log_debug(DEBUG_ARP, ???????
```

2021-05-27 12:31 UTC, DL6ER commented
This would be
``` c
if(dbID >= 0)
	log_debug(DEBUG_ARP, "...");
```

2021-05-28 08:43 UTC, DL6ER approved these changes

2021-05-28 08:56 UTC, merged