Always return full overTime data
pi-hole/FTL pull request #1736
Opened 2023-11-06 07:57 UTC by DL6ER

# What does this implement/fix?

Do not reduce the number of sent timeslots based on the real activity but instead always send everything (even if there are many zeros). This brings https://github.com/pi-hole/FTL/pull/1345 to FTL v6.0. See also the reasoning over there.

---

**Related issue or feature (if applicable):** N/A

**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** N/A

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

## Checklist:

- [x] The code change is tested and works locally.
- [x] I based my code and PRs against the repositories `developmental` branch.
- [x] I [signed off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
- [x] I [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all my commits. Pi-hole requires signatures to verify authorship
- [x] I have read the above and my PR is ready for review.

2023-11-07 21:38 UTC, yubiuser requested changes
More needs to be deleted I guess.

![Screenshot at 2023-11-07 22-38-04](https://github.com/pi-hole/FTL/assets/26622301/6d9db9fa-0c40-498b-8073-aac95d946947)

2023-11-08 08:12 UTC, DL6ER commented
Apparently, I did not scroll down far enough. I still had mobile view enabled in my browser. Anyway, I also included a small performance improvement by avoiding keeping locks too long. This can actually be measured on low-end devices.

![Screenshot from 2023-11-08 09-11-55](https://github.com/pi-hole/FTL/assets/16748619/f1ec8d21-4233-4623-b740-5e5d733f4cc7)

We see an interesting thing here: My web interface already includes the delayed rendering which - apparently - really only works when the charts comes fully into view. Indeed, when scrolling down, they appear:

![Screenshot from 2023-11-08 09-12-01](https://github.com/pi-hole/FTL/assets/16748619/5ddab2db-7b7b-4455-a0fe-467cad448480)

IMO we should improve on this, it looks odd on the first screenshot.

2023-11-08 08:24 UTC, yubiuser commented
> IMO we should improve on this, it looks odd on the first screenshot.

Feel free to tweak `delay` and `y-offset` as you like it.

2023-11-08 20:59 UTC, yubiuser approved these changes

2023-11-08 21:10 UTC, yubiuser commented
> IMO we should improve on this, it looks odd on the first screenshot.

PR https://github.com/pi-hole/web/pull/2815 reduced the necessary fraction before the animation triggers.

2023-11-09 01:47 UTC, merged