Make WAL mode for pihole-FTL.db optional
pi-hole/FTL pull request #1868
Opened 2024-01-29 15:18 UTC by DL6ER

# What does this implement/fix?

Add new config option `database.useWAL` defaulting to true making the use of the WAL journal optional for the on-disk query database. Reasons why this might be useful are given in the description of the new config option:

> **Should FTL enable Write-Ahead Log (WAL) mode for the on-disk query database (configured via files.database)?**
> It is recommended to leave this setting enabled for performance reasons. About the only reason to disable WAL mode is if you are experiencing specific issues with it, e.g., when using a database that is accessed from multiple hosts via a network share. When this setting is disabled, FTL will use SQLite3's default journal mode (rollback journal in DELETE mode).

This PR was initially triggered by [this Discourse thread](https://discourse.pi-hole.net/t/no-query-log-update-anymore-and-no-top-clients-all-and-blocked/67929), however, by now I think that WAL wasn't the issue here but specific user configuration I had not noticed before in the debug log.

---

**Related issue or feature (if applicable):** N/A

**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** N/A

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

## Checklist:

- [x] The code change is tested and works locally.
- [x] I based my code and PRs against the repositories `developmental` branch.
- [x] I [signed off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
- [x] I [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all my commits. Pi-hole requires signatures to verify authorship
- [x] I have read the above and my PR is ready for review.

2024-01-30 00:41 UTC, rdwebdesign requested changes

2024-01-30 00:41 UTC, rdwebdesign commented on src/config/config.c
> +	// a setting that will be changed very rarely, this semms the better
Typo in the comment:
```suggestion
	// a setting that will be changed very rarely, this seems the better
```

2024-01-30 00:41 UTC, rdwebdesign commented on src/database/query-table.c
> +		// - Disk I/O operations tends to be more sequential using WAL.
Another one:
```suggestion
		// - Disk I/O operations tend to be more sequential using WAL.
```

2024-02-27 16:17 UTC, rdwebdesign approved these changes
Approving, based on [user's comment](https://discourse.pi-hole.net/t/no-query-log-update-anymore-and-no-top-clients-all-and-blocked/67929/27):

> this works

2024-03-04 13:10 UTC, PromoFaux approved these changes

2024-03-04 18:40 UTC, merged