Restart FTL on change of webserver.api.cli_pw
pi-hole/FTL pull request #2041
Opened 2024-08-26 15:05 UTC by DL6ER

# What does this implement/fix?

Very simple PR, fixes #2040

---

**Related issue or feature (if applicable):** N/A

**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** N/A

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

## Checklist:

- [x] The code change is tested and works locally.
- [x] I based my code and PRs against the repositories `developmental` branch.
- [x] I [signed off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
- [x] I [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all my commits. Pi-hole requires signatures to verify authorship
- [x] I have read the above and my PR is ready for review.

2024-08-27 20:18 UTC, yubiuser requested changes
This only fixes half of the problem. It adds `cli_pw` file if the option was disabled and the file did not exist so far.
But: It does not delete `cli_pw` file when the option is changed from enabled -> disabled

2024-08-28 06:39 UTC, DL6ER commented
The file may not be deleted but its content cannot be used to log into the API any longer. Instead of FTL deleting the file on disabling of this option, it actually seems better to add this to the `postFTL` script in `core`, to ***always*** delete the file on `stop` of `pihole-FTL`.

2024-08-28 08:56 UTC, yubiuser submitted a review, later dismissed

2024-09-01 20:28 UTC, yubiuser approved these changes
Works fine.

2024-09-02 04:33 UTC, merged