API Documentation fixes
pi-hole/FTL pull request #2086
Opened 2024-10-16 22:52 UTC by irsheep

**What does this PR aim to accomplish?:**

Fix some typos in the API documentation and add a new section

**How does this PR accomplish the above?:**

Fixed an incorrect description in the "until" parameter, it was using the same description as "from"
Fixed capitalization of "Pi-hole configuration", which was creating 2 sections in API documentation, "Pi-hole Configuration" and "Pi-hole configuration"
Added a section for "Local DNS Records"  with examples how to add and remove "A" and "CNAME" records.
Removed "$ref: 'common.yaml#/components/schemas/took'" from requestBody

**Link documentation PRs if any are needed to support this PR:**

N/A

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [X] I have read the above and my PR is ready for review. *Check this box to confirm*

2024-10-16 23:03 UTC, rdwebdesign submitted a review, later dismissed

2024-10-16 23:03 UTC, rdwebdesign commented on src/api/docs/content/specs/queries.yaml
>                  - false
Here the type is `enum` (enumerated type or enumerated set), containing 2 items: `true` and `false`.

2024-10-17 16:55 UTC, irsheep commented on src/api/docs/docs.h
> +#include "hex/specs/localdns.yaml"
I have looked at this, but this seems to be normal, as docs.h does contain other includes to yaml files.

2024-10-18 12:28 UTC, DL6ER requested changes
Thank you for your submission. The spell check found a small glitch, see below.

To be honest, I am not sure how I feel about adding dedicated documentation for local DNS records where `/config` is already documented. Yes, I see how you are getting here (making it more obvious) but one might then come and ask why we are doing it for local DNS records and local CNAMEs but not for other array-like settings (e.g., DNS upstream servers) where the same `PUT`/`DELETE` can be used.

Also, there is some glitch when you leave the field empty, you get the **full config** instead:
![Screenshot](https://github.com/user-attachments/assets/fc4c54fd-8f97-4446-ac3d-22b11541730f)

2024-10-18 12:28 UTC, DL6ER commented on src/api/docs/content/specs/localdns.yaml
> +      description: The IP address (IPv4 or IPv6) and domain seperated by a 'SPACE'
There is a small typo here: `seperated ==> separated`

```suggestion
      description: The IP address (IPv4 or IPv6) and domain separated by a 'SPACE'
```

2024-10-18 12:28 UTC, DL6ER commented on src/api/docs/content/specs/localdns.yaml
> +        security: []
Why are you defining that `security` is not required?

![image](https://github.com/user-attachments/assets/4b8b86cc-7542-4b12-a64d-7b98369fe72a)


This is definitely wrong. Just leave this away and the endpoint should correctly receive standard security restrictions:

```suggestion
```

2024-10-20 12:01 UTC, irsheep commented
> Thank you for your submission. The spell check found a small glitch, see below.
> 
> To be honest, I am not sure how I feel about adding dedicated documentation for local DNS records where `/config` is already documented. Yes, I see how you are getting here (making it more obvious) but one might then come and ask why we are doing it for local DNS records and local CNAMEs but not for other array-like settings (e.g., DNS upstream servers) where the same `PUT`/`DELETE` can be used.
> 
> Also, there is some glitch when you leave the field empty, you get the **full config** instead: ![Screenshot](https://private-user-images.githubusercontent.com/16748619/377866132-fc4c54fd-8f97-4446-ac3d-22b11541730f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MjQwNTUsIm5iZiI6MTcyOTQyMzc1NSwicGF0aCI6Ii8xNjc0ODYxOS8zNzc4NjYxMzItZmM0YzU0ZmQtOGY5Ny00NDQ2LWFjM2QtMjJiMTE1NDE3MzBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDExMjkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1OWQwNWVmNWM5MjYwYjEzYmJhOGM2ZDhlMDUyYjkyZGVhYjRlZjU0MjczNjFiMDViODBlNzBjZDAyMmM2NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xiZpJSk8pgq7OmwDp4B6cASWmZ3xty5mkl4VPkTCALY)

Sorry didn't intended to close your comment without addressing this.

When I was implementing this change I thought about the same, but decided to propose it anyway for a couple of reasons
- In the previous version of Pi-hole A and CNAME records had their own API (and only realized that this is part of `/config` after it was almost done)
- The path to update or delete the DNS records requires 4 elements in the path `/config/dns/_type_/_record_` , but that is not clear in the **Pi-hole configuration** section
- to document that format when specifying the _record_. An A record uses a space "IP fqdn" and CNAME uses a comma. At first I was thinking that it was a mistake, but then realized that this is because how it written to the hosts and dnsmask files.

This one might be cheeky because just found now, the same could be said with **DNS control**

As for the glitch that is because as you mention proposed **Local DNS records** section part of the `/config` so by leaving the `type` blank in that request you're in fact requesting `/config/dns`.

2024-10-24 18:19 UTC, DL6ER commented
> As for the glitch that is because as you mention proposed **Local DNS records** section part of the `/config` so by leaving the `type` blank in that request you're in fact requesting `/config/dns`.

Yes, I know :-) My comment was more meant into the direction "is there any way to prevent this from happening?". I could have been clearer about my intention. As you have dedicated `PUT/DELETE` descriptions, you may do the same for `GET` and avoid the parameter `{type]`. Otherwise, I do seem to recall that there was once a mentioning of the `parameter` property `allowEmptyValue` as in
``` yaml
  parameters:
    record_type:
      in: path
      name: type
      schema:
        type: string
        enum:
          - hosts
          - cnameRecords
      required: true
      description: The type of DNS record hosts (A) or cnameRecord (CNAME)
      example: hosts
      allowEmptyValue: false                                 <-----------------------
```
but I haven't tested it myself.

> An A record uses a space "IP fqdn" and CNAME uses a comma.

Ah yes, right. That is in the description of `pihole.toml` and can also be queried over the API but it isn't obvious at all from the very generic/abstract OpenAPI format how the particular formatting of the individual endpoints would be.

![image](https://github.com/user-attachments/assets/d688fa40-9b20-47af-81f3-c630bea13763)
![image](https://github.com/user-attachments/assets/d514c5ea-f8b7-4d45-9cc9-3c5cd3f10dc9)

Or, of course, you don't need to know it at all if you are using https://pi.hole/admin/settings/dnsrecords which does everything for you (if configuring via the web interface).

> document that format

Where did you add something describing this? I have only see the examples.

2024-10-28 00:35 UTC, irsheep commented
> > As for the glitch that is because as you mention proposed **Local DNS records** section part of the `/config` so by leaving the `type` blank in that request you're in fact requesting `/config/dns`.
> 
> Yes, I know :-) My comment was more meant into the direction "is there any way to prevent this from happening?". I could have been clearer about my intention. As you have dedicated `PUT/DELETE` descriptions, you may do the same for `GET` and avoid the parameter `{type]`. Otherwise, I do seem to recall that there was once a mentioning of the `parameter` property `allowEmptyValue` as in
> 
> ```yaml
>   parameters:
>     record_type:
>       in: path
>       name: type
>       schema:
>         type: string
>         enum:
>           - hosts
>           - cnameRecords
>       required: true
>       description: The type of DNS record hosts (A) or cnameRecord (CNAME)
>       example: hosts
>       allowEmptyValue: false                                 <-----------------------
> ```
> 
> but I haven't tested it myself.
> 
> > An A record uses a space "IP fqdn" and CNAME uses a comma.
> 
> Ah yes, right. That is in the description of `pihole.toml` and can also be queried over the API but it isn't obvious at all from the very generic/abstract OpenAPI format how the particular formatting of the individual endpoints would be.
> 
> ![image](https://private-user-images.githubusercontent.com/16748619/379890402-d688fa40-9b20-47af-81f3-c630bea13763.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MTM1NzcsIm5iZiI6MTcyOTgxMzI3NywicGF0aCI6Ii8xNjc0ODYxOS8zNzk4OTA0MDItZDY4OGZhNDAtOWIyMC00N2FmLTgxZjMtYzYzMGJlYTEzNzYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDIzNDExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwOGM5YmE3NWJkYmM1ZmRmZjhjNGUyNDVmYzkwMTA4N2QzZGNkYjExNmVmMjM0NDI2NThkNTI1MTVlODM4YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0V2tSxuJUxkueTRr8qgPOn_PcTiQXA2E5hB4_zeK2Bw) ![image](https://private-user-images.githubusercontent.com/16748619/379890471-d514c5ea-f8b7-4d45-9cc9-3c5cd3f10dc9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MTM1NzcsIm5iZiI6MTcyOTgxMzI3NywicGF0aCI6Ii8xNjc0ODYxOS8zNzk4OTA0NzEtZDUxNGM1ZWEtZjhiNy00ZDQ1LTljYzktM2M1Y2QzZjEwZGM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDIzNDExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkYjEzMDc1ODYzMTY0ZjJlNTZlOWIwYWI5ZDk5MTg1ODc3MDQ4ZjA5ZDY1MTlhNDVhZTYxYzY0YWQyNTBkZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cyC2ckRy_8gF3C4jRb0ULPup1s6i9tjsWyPTgDWlAO0)
> 
> Or, of course, you don't need to know it at all if you are using https://pi.hole/admin/settings/dnsrecords which does everything for you (if configuring via the web interface).
> 
> > document that format
> 
> Where did you add something describing this? I have only see the examples.

I looked at the `allowEmptyValue` and it doesn't seem to work, I do agree with your suggestion to have the `GET` method added for each of the record types, it might make is less ambiguous.

It is in the description/example of the `record` parameter, don't think that makes sense adding it anywhere else.

2025-06-07 10:04 UTC, closed without merging